### ISSUE TITLE
PSR-2

### ISSUE THREAD

**Issue by rtheunissen** [logical-and/php-oauth#23]
Would you consider changing to PSR-2? While working on the pull request for #21 I couldn't help but notice gross indentation inconsistencies and I believe that this project would benefit greatly from following a framework standard such as PSR-2 (as it already applies PSR-4).

A few obvious things that would need to be updated are:
- Tabs to spaces
- No new line after control structures
- New line after class declaration

**Comment by logical-and** [comment]
Well, sounds like good idea. I will take a care about coding standard soon.
Thank you :)

**Comment by rtheunissen** [comment]
> I will take a care about coding standard soon.

I'd be happy to do it and create a pull request?

**Comment by logical-and** [comment]
Yes, it will be a great help for us all, if you do it. :)
If you working in PHPStorm, then you can use PSR-1/PSR-2 from predefined styles, and apply that style to all files.

**Comment by logical-and** [comment]
@rtheunissen Please look on updated code, is it the fresh psr-2? :)
