### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by jhnferraris** [logical-and/php-oauth#30]
I can't install the repo when I try to install our library fufulabs/fitbit

Here's my `composer.json` in fufulabs/fitbit

```
{
    "name": "fufulabs/fitbit",
    "version": "0.6",
    "type": "library",
    "description": "Fitbit library with OAuth.",
    "keywords": ["fitbit"],
    "homepage": "https://github.com/fufulabs/fitbitphp",
    "license" : "Apache-2.0",
    "authors": [
        {
            "name": "Ryan Martinsen",
            "email": "ryan@ryanware.com",
            "homepage": "http://ryanmartinsen.com"
        },
        {
            "name": "Eli White",
            "homepage": "http://eli-white.com"
        }
    ],
    "require": {
        "php": ">=5.3.0",
        "and/oauth": "0.7.*@dev"
    },
    "autoload": {
        "psr-0": {
            "Fitbit": "lib/"
        }
    }
}
```

The error when I try to install fufulabs/fitbit via composer to a different project:

```
Problem 1
    - fufulabs/fitbit dev-master requires and/oauth 0.7.*@dev -> no matching package found.
    - fufulabs/fitbit dev-master requires and/oauth 0.7.*@dev -> no matching package found.
```

Debugging it in the fufulabs/fitbit project, I can successfully install `and/oauth` but in a different project utilizing fufulabs/fitbit library requiring `and/oauth`, the `and/oauth` won't install

Any thoughts?

**Comment by jhnferraris** [comment]
Update: 

I tried adding  `"minimum-stability": "beta"` in my `composer.json` in fufulabs/fitbit but project A still won't install fufulabs/fitbit due to `and/oauth` not being found.

**Comment by jhnferraris** [comment]
Update: I am now able to install the repo but I used the stable version.

**Comment by logical-and** [comment]
I will mark main branch as stable soon. Thank you for reminder.
