### ISSUE TITLE
Classes are not loaded properly

### ISSUE THREAD

**Issue by jhnferraris** [logical-and/php-oauth#31]
Installed `and/oauth` via composer. I'm getting  `Class 'OAuth\Common\Http\Client\CurlClient' not found` when I try instantiating CurlClient.  

I've already set the namespace `use OAuth\Common\Http\Client\CurlClient;` when trying to instantiate it, it still throws a `not found` error.

**Comment by jhnferraris** [comment]
Nevermind. The updated library utilized a new client class. My bad.

**Comment by logical-and** [comment]
Reported, solved. :)
