### ISSUE TITLE
How to create a custom service

### ISSUE THREAD

**Issue by sisuwayn** [logical-and/php-oauth#34]
Hi, I have a custom oauth 1 service that is not listed in the service folder. I can clone an existing service to get it working but were would I put this file and how do I reference it?

e.g I can't leave it in the vendor folder since componser will override the directory if I update the library.

**Comment by sisuwayn** [comment]
actually just worked it out. Registered the new service and it's all good

**Comment by logical-and** [comment]
Yeah, you just need to create and register new service using ServiceFactory::registerService() method
